[platformio]
default_envs = teensy41
src_dir = examples/platformio

[env]
lib_ldf_mode = chain+
platform = teensy
framework = arduino
monitor_speed = 115200
build_flags = -std=gnu++17 -Ilib
build_unflags = -std=gnu++14

[env:teensy41]
board = teensy41

[env:teensy40]
board = teensy40

[env:euclid]
board = teensy41
build_flags = ${env.build_flags} -DTMS_DEMO=1

[env:stereo]
board = teensy41
build_flags = ${env.build_flags} -DTMS_DEMO=2

[env:orbit]
board = teensy41
build_flags = ${env.build_flags} -DTMS_DEMO=3

[env:audio_lab41]
platform = teensy@5.2.0
lib_ldf_mode = deep+
board = teensy41
build_flags = ${env.build_flags} -DTMS_DEMO=4

[env:audio_lab40]
platform = teensy@5.2.0
lib_ldf_mode = deep+
board = teensy40
build_flags = ${env.build_flags} -DTMS_DEMO=4
